<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>str_errorline</name>
   <tag></tag>
   <elementGuidId>f58c38ae-551e-44ca-8d3f-fad0716c3448</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span[id=&quot;repeatedPassword.errors&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
